application: samlib-parser
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /.*
  script: main.app

builtins:
- appstats: on

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest